-- 1. artist_pdf_jobs
ALTER TABLE artist_pdf_jobs ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

-- 2. order_items
ALTER TABLE order_items ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE order_items ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

-- 3. tickets
ALTER TABLE tickets ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

-- 4. checkin_logs
ALTER TABLE checkin_logs ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE checkin_logs ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

-- 5. payment_logs
ALTER TABLE payment_logs ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

-- 6. guest_lists
ALTER TABLE guest_lists ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE guest_lists ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

-- 7. batch_logs
ALTER TABLE batch_logs ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE batch_logs ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

-- 8. notifications
ALTER TABLE notifications ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
