spring:
  application:
    name: ticketbox-api
  profiles:
    default: dev
  jackson:
    serialization:
      write-dates-as-timestamps: false
  modulith:
    detection-strategy: explicitly-annotated

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
